### ISSUE TITLE
[Bug] Annotate electrcial connectivity of modules (strings) -> plant_ids mixed up

### ISSUE THREAD

**Issue by 3rdMonkeyProject** [LukasBommes/PV-Hawk-Viewer#3]
The order of plant_ids is mixed up, should be like **$InverterID_$TrackerID_$ArrayID_$StringID_$ModuleID** instead of **$TrackerID_$ArrayID_$InverterID_$StringID_$ModuleID** and the $ModuleIDs should start with **01** instead of **00**

Best regards,
Tobias

**Comment by LukasBommes** [comment]
fixed in 87631f52f9131dfe64d8485f1906cbe16c8e40fd
